"""Initial migration

Revision ID: 6408636d3256
Revises: 
Create Date: 2026-02-25 22:40:22.783212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6408636d3256'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=200), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('bloodGroup', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lastDonationDate', sa.String(length=50), nullable=True),
    sa.Column('availabilityStatus', sa.String(length=50), nullable=True),
    sa.Column('chronicIllness', sa.String(length=20), nullable=True),
    sa.Column('recentSurgery', sa.String(length=20), nullable=True),
    sa.Column('medication', sa.String(length=20), nullable=True),
    sa.Column('infectionHistory', sa.String(length=20), nullable=True),
    sa.Column('doctorAdvised', sa.String(length=20), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('bloodGroup', sa.String(length=10), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receiver')
    op.drop_table('donor')
    # ### end Alembic commands ###
